-- Core schema for the expense tracker.
-- Enum-like columns are stored as VARCHAR with CHECK constraints to keep the
-- schema portable and to match JPA's EnumType.STRING mapping.
-- Primary keys use GENERATED BY DEFAULT AS IDENTITY to work with JPA's
-- GenerationType.IDENTITY.

CREATE TABLE departments (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               VARCHAR(150) NOT NULL UNIQUE,
    team_lead_id       BIGINT,
    finance_manager_id BIGINT
);

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    full_name     VARCHAR(255) NOT NULL,
    role          VARCHAR(32)  NOT NULL,
    department_id BIGINT REFERENCES departments (id),
    enabled       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT chk_users_role CHECK (role IN ('EMPLOYEE', 'TEAM_LEAD', 'FINANCE_MANAGER'))
);

-- Department approver FKs reference users; added after users exists.
ALTER TABLE departments
    ADD CONSTRAINT fk_dept_team_lead FOREIGN KEY (team_lead_id) REFERENCES users (id),
    ADD CONSTRAINT fk_dept_finance_manager FOREIGN KEY (finance_manager_id) REFERENCES users (id);

CREATE TABLE expenses (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submitter_id  BIGINT        NOT NULL REFERENCES users (id),
    department_id BIGINT        NOT NULL REFERENCES departments (id),
    category      VARCHAR(32)   NOT NULL,
    amount        NUMERIC(12,2) NOT NULL,
    currency      VARCHAR(3)    NOT NULL DEFAULT 'USD',
    description   VARCHAR(1000) NOT NULL,
    status        VARCHAR(32)   NOT NULL DEFAULT 'PENDING_TEAM_LEAD',
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT chk_expenses_category CHECK (category IN ('TRAVEL', 'MEALS', 'SUPPLIES', 'SOFTWARE', 'OTHER')),
    CONSTRAINT chk_expenses_status CHECK (status IN ('PENDING_TEAM_LEAD', 'PENDING_FINANCE', 'APPROVED', 'REJECTED')),
    CONSTRAINT chk_expenses_amount_positive CHECK (amount > 0)
);

CREATE INDEX idx_expenses_submitter ON expenses (submitter_id);
CREATE INDEX idx_expenses_status_dept ON expenses (status, department_id);

CREATE TABLE receipts (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expense_id   BIGINT       NOT NULL UNIQUE REFERENCES expenses (id) ON DELETE CASCADE,
    filename     VARCHAR(255) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    size_bytes   BIGINT       NOT NULL,
    data         BYTEA        NOT NULL
);

CREATE TABLE approval_events (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expense_id BIGINT        NOT NULL REFERENCES expenses (id) ON DELETE CASCADE,
    actor_id   BIGINT        NOT NULL REFERENCES users (id),
    action     VARCHAR(32)   NOT NULL,
    comment    VARCHAR(1000),
    created_at TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT chk_approval_action CHECK (action IN (
        'SUBMITTED', 'TEAM_LEAD_APPROVED', 'TEAM_LEAD_REJECTED', 'FINANCE_APPROVED', 'FINANCE_REJECTED'))
);

CREATE INDEX idx_approval_events_expense ON approval_events (expense_id);
